export const GroupErrors = {
  INVALID_NAME:         'INVALID_NAME',
  NO_OWNER:             'NO_OWNER',
  GROUP_NOT_FOUND:      'GROUP_NOT_FOUND',
  ALREADY_MEMBER:       'ALREADY_MEMBER',
  NOT_MEMBER:           'NOT_MEMBER',
  NOT_ADMIN:            'NOT_ADMIN',
  NOT_OWNER:            'NOT_OWNER',
  REQUEST_NOT_FOUND:    'REQUEST_NOT_FOUND',
  REQUEST_ALREADY_SENT: 'REQUEST_ALREADY_SENT',
  CANNOT_REMOVE_OWNER:  'CANNOT_REMOVE_OWNER',
  CANNOT_PROMOTE_OWNER: 'CANNOT_PROMOTE_OWNER',
} as const;