export const UserErrors = {
  INVALID_EMAIL:    'INVALID_EMAIL',
  INVALID_NAME:     'INVALID_NAME',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  EMAIL_IN_USE:     'EMAIL_IN_USE',
  USER_NOT_FOUND:   'USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
} as const;